# This is a basic workflow to help you get started with Actions

name: flutter

on:
  push:
    branches: [ master, prod ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - name: Insert git sha
        run: |
          sed -i -e "s|GIT_SHA_REPLACE|$GITHUB_SHA|g" lib/config.dart
      - name: Insert build date
        run: |
          sed -i -e "s|BUILD_DATE_REPLACE|$(date)|g" lib/config.dart
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.x'
      - run: flutter pub get
      #- run: flutter test
      - run: flutter dartfmt -n --set-exit-if-changed lib
      - run: flutter analyze
      - if: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
        uses: bluefireteam/flutter-gh-pages@v7
      - if: ${{ github.event_name == 'push' && github.ref_name == 'prod' }}
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          targetBranch: prod-gh-pages
